weights: weights/yolov5s6.pt
cfg: models/yolov5s6_trash.yaml
data: data/voc_trash.yaml
hyp: data/hyp.scratch.yaml
epochs: 120
batch_size: 8
img_size:
- 1280
- 1280
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 4
project: runs/train
entity: null
name: base+P6
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
world_size: 1
global_rank: -1
save_dir: runs/train/base+P6
total_batch_size: 8
